ALTER TABLE `users`
MODIFY COLUMN `profile_photo` LONGTEXT NULL;

ALTER TABLE `users`
MODIFY COLUMN `facial_vector` LONGTEXT NULL;

ALTER TABLE `users`
MODIFY COLUMN `facial_descriptor` LONGTEXT NULL;